services:
    whisper:
        image: onerahmet/openai-whisper-asr-webservice:v1.10.0-gpu
        environment:
            - ASR_ENGINE=faster_whisper
            - ASR_MODEL=large-v3-turbo
            - ASR_DEVICE=cuda
        volumes:
            - ./cache:/root/.cache

        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]

    curler:
        build: .
        volumes:
            - ./input:/input
            - ./output:/output
            - ./archive:/archive